### ISSUE TITLE
关于注释的问题

### ISSUE THREAD

**Issue by moonmemories** [AriesHoo/GitHubDemo#1]
最近在给自己项目添加注释，使用了你的方法，可是依赖下来还是没有效果。然后依赖了你的这个项目发现也没有注释啊。

**Comment by AriesHoo** [comment]
你有试过BaseRecyclerViewAdapterHelper 没有依赖下来有没有注释。。我的方法是参考他的。如果也没有估计就得另外想办法了。我的所有lib都是这种模式。在自己开发和同事协同都是有注释的

**Comment by moonmemories** [comment]
@AriesHoo 谢谢回复，今天同事的电脑依赖了我这个库就有注释了。看来是我studio的问题啦，哈哈。
